#!/usr/bin/env python
"""
This program extracts data from RPM and SRPM packages and stores it in
a database for later querying.

based on the srpm script of similar function copyright (c) 2005 Stew Benedict <sbenedict@mandriva.com>
copyright (c) 2007-2009 Vincent Danen <vdanen@linsec.ca>

$Id$
"""

RQ_VERSION = '0.5'
RQ_PROG    = 'rqs'
RQ_TYPE    = 'source'

import optparse, os, sys, logging
import rq.db
import rq.basics
import rq.tag
import rq.source


if __name__ == '__main__':
    sys.stdout.write("%s %s ($Id$)\n\n" % (RQ_PROG, RQ_VERSION))
    # TODO: add options to search files by ownership and sgid/suid status

    p = optparse.OptionParser(description="RPM package query tool",
                              prog=RQ_PROG,
                              version="%prog " + RQ_VERSION,
                              usage="%prog [-h] [-v] [-c <directory>] [-[q|r|p|z] <substring>] [-t <tag>]")
    p.add_option('-n', '--config', dest="conffile", metavar="FILE",
                 help="Optional configuration file")
    p.add_option('-C', '--count', dest="count", default=False, action="store_true",
                 help="Only output the count of query matches")
    p.add_option('-d', '--debug', dest="debug", default=False, action="store_true",
                 help="Enable debugging output")
    p.add_option('-e', '--extrainfo', dest="extrainfo", default=False, action="store_true",
                 help="Show extra info (version, release, date)")
    p.add_option('-i', '--ignorecase', dest="ignorecase", default=False, action="store_true",
                 help="Case insensitive search")
    p.add_option('-l', '--list', dest="list", default=False, action="store_true",
                 help="List database tags")
    p.add_option('-p', '--patch', dest="patch", default=False, action="store_true",
                 help="List patched files when examining a src.rpm")
    p.add_option('-P', '--progress', dest="progress", default=False, action="store_true",
                 help="Show processing progress")
    p.add_option('-Q', '--quiet', dest="quiet", default=False, action="store_true",
                 help="Quiet query - show tag and package name only (or numeric count only)")
    p.add_option('-s', '--skip-tar', dest="skiptar", default=False, action="store_true",
                 help="Skip tarfile extract when examining a src.rpm")
    p.add_option('-S', '--source-only', dest="sourceonly", default=False, action="store_true",
                 help="Limit query to source files (no patches)")
    p.add_option('-T', '--suppresstag', dest="suppresstag", default=False, action="store_true",
                 help="Suppress Tag and Path label output for queries")
    p.add_option('-x', '--statistics', dest="stats", default=False, action="store_true",
                 help="Show database statistics")
    p.add_option('-v', '--verbose', dest="verbose", default=False, action="store_true",
                 help="Verbose output")
    dbgroup = optparse.OptionGroup(p, "Database Options")
    dbgroup.add_option('-a', '--add', dest="addfile", metavar="FILE",
                       help="Add a " + RQ_TYPE + " rpm entry with TAG to the database")
    dbgroup.add_option('-c', '--createpath', dest="createpath", metavar="DIR",
                       help="Create database entries with TAG from a " + RQ_TYPE + " rpm DIR")
    dbgroup.add_option('-D', '--delete', dest="tagdelete", metavar="TAG",
                       help="Delete all TAG entries")
    dbgroup.add_option('-f', '--file', dest="src_examine", metavar="FILE",
                       help="Examine a src.rpm FILE and output to stdout")
    dbgroup.add_option('-t', '--tag', dest="tag", metavar="TAG",
                       help="TAG for created database entries or database queries")
    dbgroup.add_option('-u', '--update', dest="tagupdate", metavar="TAG",
                       help="Update TAG entries (new/removed files in directory)")
    p.add_option_group(dbgroup)
    group = optparse.OptionGroup(p, "Query Options")
    group.add_option('-q', '--query', dest="query", metavar="STRING",
                     help="Query database for substring match on files")
    group.add_option('-b', '--buildreqs', dest="buildreqs", metavar="STRING",
                     help="Query database for substring match on BuildRequires")
    group.add_option('-o', '--info', dest="showinfo", metavar="STRING",
                     help="Show all info on specified srpm")
    group.add_option('-z', '--ctags', dest="ctags", metavar="STRING",
                     help="Query database for substring match on ctags data (functions, etc.)")
    p.add_option_group(group)

    # 'arguments' is a tuple of non-optioned things
    (options, arguments) = p.parse_args()

    if len(sys.argv) == 1:      # no arguments passed
        p.print_help()
        sys.exit(0)

    # setup the options
    if options.verbose and options.quiet:
        p.error("--quiet and --verbose are mutually exclusive")
    if options.tag and options.tagdelete:
        p.error("--tag and --delete are mutually exclusive; you do not need to use --tag")

    # setup logging facilities
    LOG_FILENAME = '%s/%s.log' % (os.getcwd(), RQ_PROG)
    LEVELS = {'debug'  : logging.DEBUG,
              'info'   : logging.INFO,
              'warning': logging.WARNING}

    if options.debug:
        FILELEVEL = LEVELS.get('debug', logging.NOTSET)
        CONSLEVEL = LEVELS.get('debug', logging.NOTSET)
        FILEFMT   = '%(asctime)s %(filename)s(%(funcName)s[%(lineno)d]): %(levelname)s: %(message)s'

    if options.verbose:
        FILELEVEL = LEVELS.get('info', logging.NOTSET)
        CONSLEVEL = LEVELS.get('info', logging.NOTSET)
        FILEFMT   = '%(asctime)s %(message)s'

    if not options.verbose and not options.debug:
        FILELEVEL = LEVELS.get('info', logging.NOTSET)
        CONSLEVEL = LEVELS.get('warning', logging.NOTSET)
        FILEFMT   = '%(asctime)s %(message)s'

    logging.basicConfig(level=FILELEVEL,
                        format=FILEFMT,
                        datefmt='%b %d %H:%M:%S',
                        filename=LOG_FILENAME,
                        filemode='a')
    console = logging.StreamHandler()
    console.setLevel(CONSLEVEL)
    CONSFMT = logging.Formatter('%(message)s')
    console.setFormatter(CONSFMT)
    logging.getLogger('').addHandler(console)

    logging.debug("%s starting, debug mode enabled; type => %s" % (RQ_PROG, RQ_TYPE))

    config = rq.basics.Config(options.conffile)
    db     = rq.db.DB(RQ_TYPE, config)

    # get the name of the database we want to talk to
    config['database'] = db.get_dbname()

    rtag = rq.tag.Tag(db, RQ_TYPE, config)

    rcommon = rq.basics.Common(options, rtag, RQ_TYPE)

    rqs = rq.source.Source(db, config, options, rtag, rcommon)

    # start doing useful things
    if options.list:
        rtag.list()

    if options.stats:
        if options.tag:
            rtag.showdbstats(options.tag)
        else:
            rtag.showdbstats()

    if options.tag:
        logging.debug('Tag:\t%s\n' % options.tag)

    if options.tagdelete:
        rtag.delete_entries(options.tagdelete)
        sys.exit(0)

    if options.tagupdate:
        rtag.update_entries(options.tagupdate)
        sys.exit(0)

    if options.query:
        rqs.query('files')
        sys.exit(0)

    if options.ctags:
        rqs.query('ctags')
        sys.exit(0)

    if options.buildreqs:
        rqs.query('buildreqs')
        sys.exit(0)

    if options.showinfo:
        rqs.showinfo()
        sys.exit(0)

    if options.src_examine:
        rqs.examine(options.src_examine)
        sys.exit(0)

    # this option is strange... it must be for adding a file, but should a single file
    # have a new tag?  or can we add it (despite the path) to an existing tag?
    # TODO: it also needs to be able to support numerous files at once
    if options.addfile:
        if not options.tag:
            logging.critical('The --add option requires a tag entry!')
            sys.exit(1)

        # are we passed a file, or directory?
        if os.path.isfile(options.addfile):
            # passed a file, we want the path
            path = os.path.abspath(os.path.dirname(options.addfile))
        else:
            # passed a directory
            path = os.path.abspath(options.addfile)

        havetag = rtag.lookup(options.tag)

        if not havetag:
            logging.critical('The --add option requires a tag that already exists!')
            sys.exit(1)

        if path != havetag['path']:
            logging.critical('Tag (%s) is already in the database with path: %s' % (options.tag, havetag['path']))
            logging.critical('Cannot add to an existing tag from a different path!  Unwilling to use %s to add a new file!' % path)
            sys.exit(1)

        # the rest of this just makes no sense as-is so bail
        print 'The --add option is non-functional.  Sorry.'
        sys.exit(1)

        addfiles = []
        addfiles.append(path)

        if len(arguments) > 0:
            addfiles.extend(arguments)

        for afile in addfiles:
            print afile
            #record_add(options.tag, afile, RQ_TYPE)

        sys.exit(0)

    if options.createpath:
        createpath = os.path.abspath(options.createpath)
        logging.debug('Dir:\t%s' % createpath)
        if not options.tag:
            sys.stdout.write('The --create option requires a tag entry!\n')
            sys.exit(1)

        sys.stdout.write('Searching for rpms to import...\n\n')
        rqs.rpm_add_directory(options.tag, createpath)
        sys.exit(0)

    # if we get here, we have completely invalid arguments
    p.print_help()
    sys.exit(0)
